default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Buildify_development
test:
  <<: *default
  database: Buildify_test
production:
  <<: *default
  database: Buildify_production
  username: Buildify
  password: <%= ENV['BUILDIFY_DATABASE_PASSWORD'] %>
